# Generated by Django 5.1.1 on 2024-11-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("y_sku", models.CharField(max_length=100, null=True)),
                ("ozon_sku", models.CharField(max_length=100, null=True)),
                ("wb_sku", models.CharField(max_length=100, null=True)),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("spb", "СПБ"),
                            ("msk", "МСК"),
                            ("samara", "Самара"),
                            ("kazan", "Казань"),
                            ("krasnodar", "Краснодар"),
                            ("nn", "НН"),
                            ("ekb", "ЕКБ"),
                            ("rnd", "РНД"),
                            ("nsk", "НСК"),
                        ],
                        max_length=10,
                    ),
                ),
                ("y_warehouse", models.IntegerField(null=True)),
                ("ozon_warehouse", models.IntegerField(null=True)),
                ("wb_warehouse", models.IntegerField(null=True)),
                ("stock", models.IntegerField(default=0)),
                ("prev_ozon_stock", models.IntegerField(default=0)),
                ("prev_stock", models.IntegerField(default=0)),
                ("ozon_reserved", models.IntegerField(default=0)),
                ("y_reserved", models.IntegerField(default=0)),
                ("wb_reserved", models.IntegerField(default=0)),
                ("avito_reserved", models.IntegerField(default=0)),
                ("last_user", models.CharField(default="On build", max_length=100)),
                ("last_time", models.CharField(max_length=20)),
                ("is_sync", models.BooleanField(default=True)),
                ("is_modified", models.BooleanField(default=False)),
                ("is_complement", models.BooleanField(default=False)),
            ],
        ),
    ]
