name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H "$SERVER_IP" > ~/.ssh/known_hosts

    - name: Add SSH key
      run: |
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_rsa

    - name: Copy files to server
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        scp -i ~/.ssh/id_rsa -r ./* $SERVER_USER@$SERVER_IP:/home/dev/Cloud-Stock

    - name: Restart service on server
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        ssh -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_IP 'bash -s' << 'ENDSSH'
          cd /home/dev/Cloud-Stock
          bash build.sh deploy
        ENDSSH